source 'https://rubygems.org'

gem 'rails',                '4.2.2'
gem 'sass-rails',           '5.0.2'
gem 'uglifier',             '2.5.3'
gem 'coffee-rails',         '4.1.0'
gem 'jquery-rails',         '4.0.3'
gem 'animate.css-rails', '~> 3.2.0'
#gem 'turbolinks',           '2.3.0'
gem 'twitter-bootstrap-rails'
gem 'devise-bootstrap-views'
gem 'bootstrap-sass',       '~> 3.2.0'
gem 'autoprefixer-rails'
gem 'therubyracer', :platform => :ruby
gem 'jbuilder',             '2.2.3'
gem 'devise'
gem 'simple_form'
gem 'sdoc',                 '0.4.0', group: :doc
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'yelp', require: 'yelp'


group :development, :test do
  gem 'sqlite3',     '1.3.9'
  gem 'byebug',      '3.4.0'
  #gem 'web-console', '2.0.0.beta3'
  gem 'spring',      '1.1.3'
end

group :production do
  gem 'pg',             '0.17.1'
  gem 'rails_12factor', '0.0.2'
end